[greeter]
background=/usr/share/backgrounds/kalipwm/obsidian-login.png
user-background=false
theme-name=KaliPWM-Obsidian
icon-theme-name=Flat-Remix-Blue-Light
font-name=JetBrainsMono Nerd Font 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=slight
xft-rgba=rgb
hide-user-image=true
round-user-image=true
highlight-logged-user=true
indicators=~session;~spacer;~layout;~a11y;~clock;~power;
clock-format=%H:%M  ·  %d %b %Y
keyboard=onboard
screensaver-timeout=60
transition-duration=250
transition-type=ease-in-out
