; KaliPWM V1 — Obsidian Tactical custom Polybar modules

[module/launcher]
type = custom/text
content = "  "
content-foreground = ${color.accent}
click-left = ~/.config/polybar/forest/scripts/launcher.sh &
click-right = ~/.config/polybar/forest/scripts/style-switch.sh &

[module/sysmenu]
type = custom/text
content = " 󰐥 "
content-foreground = ${color.foreground-muted}
click-left = ~/.config/polybar/forest/scripts/powermenu.sh &

[module/sep]
type = custom/text
content = "│"
content-foreground = ${color.sep}

[module/target]
type = custom/script
exec = ~/.local/bin/target.sh
interval = 1
format = <label>
label = " %output% "
label-background = ${color.background-alt}
label-padding = 1

[module/system-profile]
type = custom/script
exec = ~/.local/bin/kalipwm-profile
interval = 3
format = <label>
label = %output%
label-foreground = ${color.accent}

[module/telemetry]
type = custom/script
exec = ~/.local/bin/kalipwm-telemetry
interval = 3
format = <label>
label = %output%
label-foreground = ${color.foreground-muted}

[module/network-status]
type = custom/script
exec = ~/.local/bin/kalipwm-network
interval = 2
format = <label>
label = %output%
label-foreground = ${color.foreground}

[module/vpn-status]
type = custom/script
exec = ~/.local/bin/kalipwm-vpn
interval = 2
format = <label>
label = %output%
label-foreground = ${color.healthy}

[module/battery-status]
type = custom/script
exec = ~/.local/bin/kalipwm-battery
interval = 10
format = <label>
label = %output%
label-foreground = ${color.foreground}
